### ISSUE TITLE
Tailwind & duplicate code

### ISSUE THREAD

**Issue by daybugging** [stefanzweifel/vue-tailwind-css-modules-demo#5]
Hey there,
I read your article on using TailwindCSS together with VueJS. Regarding your issue with duplicate code when used with components: did you try [`postcss-combine-duplicated-selectors`](https://github.com/ChristianMurphy/postcss-combine-duplicated-selectors)?

Best regards,
daybuggin

**Comment by stefanzweifel** [comment]
Looks like tailwindcss@0.6.3 fixes this issue: https://github.com/tailwindcss/tailwindcss/releases/tag/v0.6.2#allow-applying-classes-that-arent-defined-but-would-be-generated

I've already pushed some code in a separate branch. Will do some more testing and then create a nice PR and update my original article.

Branch: https://github.com/stefanzweifel/vue-tailwind-css-modules-demo/tree/upgrade-to-tailwind-0.6
